blank_issues_enabled: false
contact_links:
  - name: Ask a Question
    url: https://github.com/Oldhimaster1/3ds-Google-Maps/issues/new?labels=question
    about: Not a bug or feature request? Open a question issue here.
