#!/usr/bin/env python3
"""
generate_cert.py
Generate a self-signed TLS certificate + private key for the 3DS GPS HTTPS server.

Outputs: include/gps_server_cert.h
         DER-encoded certificate and RSA-2048 private key as C byte arrays.

Requirements:
    pip install cryptography

Run once before building the 3DS app. Re-run only if you want a new certificate
(the phone will need to accept the trust warning again after regeneration).
"""

import os
import sys
import datetime


def bytes_to_c_array(data: bytes, name: str) -> str:
    lines = [f"static const unsigned char {name}[] = {{"]
    for i in range(0, len(data), 16):
        chunk = data[i : i + 16]
        hex_str = ", ".join(f"0x{b:02x}" for b in chunk)
        lines.append(f"    {hex_str},")
    lines.append("};")
    lines.append(f"static const unsigned int {name}_len = {len(data)}u;")
    return "\n".join(lines)


def main() -> None:
    try:
        from cryptography import x509
        from cryptography.x509.oid import NameOID
        from cryptography.hazmat.primitives import hashes, serialization
        from cryptography.hazmat.primitives.asymmetric import rsa
    except ImportError:
        print("ERROR: 'cryptography' library not found.")
        print("Install it with:  pip install cryptography")
        sys.exit(1)

    print("Generating RSA-2048 private key ...")
    key = rsa.generate_private_key(
        public_exponent=65537,
        key_size=2048,
    )

    print("Generating self-signed X.509 certificate ...")
    subject = issuer = x509.Name(
        [
            x509.NameAttribute(NameOID.COMMON_NAME, "3ds-gps-server"),
            x509.NameAttribute(NameOID.ORGANIZATION_NAME, "3DS Homebrew GPS"),
        ]
    )

    now = datetime.datetime.now(datetime.timezone.utc)
    cert = (
        x509.CertificateBuilder()
        .subject_name(subject)
        .issuer_name(issuer)
        .public_key(key.public_key())
        .serial_number(x509.random_serial_number())
        .not_valid_before(now)
        .not_valid_after(now + datetime.timedelta(days=3650))  # 10 years
        .add_extension(
            x509.BasicConstraints(ca=True, path_length=None), critical=True
        )
        .sign(key, hashes.SHA256())
    )

    # DER-encoded certificate (passed to SSL_CTX_use_certificate_ASN1)
    cert_der = cert.public_bytes(serialization.Encoding.DER)

    # DER-encoded RSA private key in PKCS#1 / TraditionalOpenSSL format.
    # This is loaded with SSL_CTX_use_RSAPrivateKey_ASN1() on the 3DS.
    key_der = key.private_bytes(
        encoding=serialization.Encoding.DER,
        format=serialization.PrivateFormat.TraditionalOpenSSL,
        encryption_algorithm=serialization.NoEncryption(),
    )

    cert_array = bytes_to_c_array(cert_der, "gps_server_cert_der")
    key_array  = bytes_to_c_array(key_der,  "gps_server_key_der")

    header = f"""\
/*
 * gps_server_cert.h  —  Auto-generated by tools/generate_cert.py
 *
 * Self-signed TLS certificate and RSA-2048 private key for the
 * 3DS GPS HTTPS server.  Re-run generate_cert.py to regenerate.
 *
 * Valid from: {now.strftime('%Y-%m-%d')}
 * Expires   : {(now + datetime.timedelta(days=3650)).strftime('%Y-%m-%d')}
 *
 * Security note: the private key is embedded in the 3DS binary.
 * For homebrew personal use this is acceptable.  Do NOT use this
 * certificate for anything security-sensitive.
 */
#ifndef GPS_SERVER_CERT_H
#define GPS_SERVER_CERT_H

/* DER-encoded X.509 self-signed certificate */
{cert_array}

/* DER-encoded RSA-2048 private key (PKCS#1 / TraditionalOpenSSL format) */
{key_array}

#endif /* GPS_SERVER_CERT_H */
"""

    script_dir   = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(script_dir)
    out_path     = os.path.join(project_root, "include", "gps_server_cert.h")

    with open(out_path, "w") as f:
        f.write(header)

    print(f"Written to : {out_path}")
    print(f"Certificate: {len(cert_der)} bytes")
    print(f"Private key: {len(key_der)} bytes")
    print()
    print("Next steps:")
    print("  1. Build OpenSSL for 3DS: bash tools/build_openssl_3ds.sh")
    print("  2. Rebuild the app      : make   (from MSYS bash with devkitPro)")
    print("  3. Copy .3dsx to SD and run.")
    print("  4. In-app: Settings → GPS → Source: Server → tap GPS button.")
    print("  5. On phone: open https://<3DS-IP>:8443, accept cert warning.")


if __name__ == "__main__":
    main()
